PyErr_NewException("collectd.CollectdError", NULL, errordict);