archive_set_error(&a->archive, 0,
		    "Can't add archive to itself")